%require "3.2"
%language "c++"
%define api.namespace {yy}
%define api.parser.class {parser}
%define api.value.type variant
%define api.token.constructor
%define parse.error verbose
%defines
%output "parser.cpp"
%locations
%define api.location.file "location.hpp"
%code requires{
  namespace yy {
    class Lexer;  // Generated by reflex with namespace=yy lexer=Lexer lex=yylex
  }
  class NateParser;
  #include "Expr.h"
  #include "Type.h"
}
%parse-param { yy::Lexer& lexer } { NateParser& nate }
%code{
  #include "lex.yy.h"  // header file generated with reflex --header-file
  #include "NateParser.h"
  #undef yylex
  #define yylex lexer.lex  // Within bison's parse() we should invoke lexer.yylex(), not the global yylex()

  bool outputEnd = true;
  bool inputEnd = true;
  bool prevWasValue = false;
  std::stack<Expr> ifExpr;
  std::stack<std::string> ifId;
  std::string forId;
	std::list<Code*> curParsedCodes;
}

%define api.token.prefix {TOK_}
%token <std::string> IDENTIFIER "identifier"
%token <std::string> NUMBER "number"
%token <std::string> FRACTION "fraction"
%token <std::string> STRING "string"
%token <std::string> BOOL "bool"
%token <std::string> WORD "word"
%token EOF 0 "end of file"
%token BEGIN "begin block"
%token END "end block"
%token ALIAS "alias"
%token IMPORT "import"
%token PROGRAM "program"
%token SCOPE "scope"
%token ERR "error"
%token VAR "var"
%token CONST "const"
%token CODE "code"
%token DEFINE "define"
%token IF "if"
%token ELSE "else"
%token OUTPUT "output"
%token INPUT "input"
%token IS "is"
%token OF "of"
%token IN "in"
%token LOOP "loop"
%token WHILE "while"
%token FOR "for"
%token DOWNTO "down-to"
%token TO "to"
%token STEP "step"
%token RETURN "return"
%token INOUT "inout"
%token RECORD "record"
%token COL ":"
%token ASSIGN ":="
%token EOS "\n"
%token COMMA ","
%token CONCAT "&"
%token OPENPAR "("
%token CLOSEPAR ")"

%type <std::string>              id;
%type <std::string>              arg-id;
%type <std::vector<std::string>> id-list;
%type <TypePtr>                  is-type;
%type <TypePtr>                  type;
%type <std::string>              type-extra;
%type <std::string>              inout;
%type <bool>                     var;
%type <std::vector<Expr>>        var-init-assign;
%type <std::vector<Expr>>        var-init-list;
%type <std::vector<Expr>>        expr-list;
%type <Expr>                     var-init;
%type <bool>                     for-to;
%type <Expr>                     step;
%type <Expr>                     expr;
%type <Expr>                     expr-at-end-of-statement;
%type <Expr>                     expr-part;
%type <Expr>                     expr-part-list;
%type <Expr>					           expr-non-word;
%type <Expr>					           expr-word;
%type <std::string>              string;

%%

prog-statement-list:
	  prog-statement opt-eos
  | prog-statement-list prog-statement
  ;

prog-statement:
	  import
  | alias
  | program
  | code
  | define
  | record-statement
  | var-statement
  | EOS
  ;
  
opt-eos:
    %empty
  | EOS opt-eos
  ;

alias:
    ALIAS STRING[STR1] STRING[STR2]
      { nate.addAlias(unquote($STR1), unquote($STR2)); }
  ;

import:
    IMPORT WORD
      { nate.import($WORD); }
  ;

program:
	  PROGRAM COL 
		  { nate.codeStartProgram(); }
	  BEGIN 
		  statement-list
	  END
		  { nate.codeEndProgram(); }
  ;
  
statement-list:
    statement
  | statement-list statement
  ;

statement: 
	  var-statement
  | scope-statement
  | assign-statement
  | output-statement
  | input-statement
  | if-statement
  | loop-statement
  | return-statement
  | record-statement
  | expr-statement
  | EOS
  ;

define:
	  DEFINE 
		  { 
			  nate.addDefine();
			  lexer.pushState(Lexer::ARGS);
		  }
	  arg-list call-return COL
		  { 
			  lexer.popState();
			  lexer.pushState(Lexer::DEFINE);
			  nate.declareDefine();
		  }
	  BEGIN
		  statement-list
	  END
		  { 
			  lexer.popState(); 
			  nate.endDefine();
		  }
  ;

code:
	  CODE 
		  { 
			  nate.addCode();
        curParsedCodes.push_back(&nate.curCode());
			  lexer.pushState(Lexer::ARGS);
		  }
	  code-start
	  code-list call-return COL
		  { 
			  lexer.popState();
			  lexer.pushState(Lexer::CODE);
		  }
	  BEGIN
		  code-stat-list
	  END
		  { 
			  lexer.popState();
			  nate.endCode();

        for (auto code : curParsedCodes)
        {
          if (&nate.curCode() != code)
          {
            code->copyFrom(nate.curCode());
          }
        }

        curParsedCodes.clear();
		  }
  ;

code-list:
    code-decl
  | code-list COMMA 
      {
			  nate.endCode();
			  nate.addCode();
        curParsedCodes.push_back(&nate.curCode());
      }
    code-decl
  ;

code-decl:
	  arg-list
  ;

code-start:
    NUMBER 
		  { 
			  nate.curCode().setPriority(atoi($NUMBER.c_str())); 
		  }
  ;

code-stat-list:
    code-stat
  | code-stat-list code-stat
  | BEGIN code-stat-list END
  ;

code-stat:
    WORD
		  { nate.curCode().addCodeStatWord($WORD); }
  | id
		  { nate.curCode().addCodeStatId($id); }
  ;
  
arg-list:
    arg
  | arg-list arg
  ;

arg:
    WORD
		  { nate.addArgWord($WORD); }
  | OPENPAR inout arg-id[id] IS type 
		  { 
			  auto id = std::make_shared<Identifier>(nate.curScope(), $id, $type);
			  nate.addIdentifier(id);
		    nate.curMethod().addArgId(id);
        if (!$inout.empty())
        {
          nate.curMethod().curArg().setArgFlag($inout);
        }
		  }
    opt-arg-flags CLOSEPAR
  | id-with-arg-flags
  ;

id-with-arg-flags:
    OPENPAR inout arg-id[id] IS
		{ 
			auto id = std::make_shared<Identifier>(nate.curScope(), $id, std::make_shared<Type>(""));
			nate.addIdentifier(id);
		  nate.curMethod().addArgId(id);
      if (!$inout.empty())
      {
        nate.curMethod().curArg().setArgFlag($inout);
      }
		}
		arg-flags CLOSEPAR
  ;
 
arg-id:
    id
  | WORD
  ;

inout:
  %empty
    { $$ = ""; }
  | INOUT
    { $$ = "inout"; }
  ;
       
arg-flags:
    OPENPAR arg-flag-list CLOSEPAR
  ;

opt-arg-flags:
    %empty
  | arg-flags
  ;

arg-flag-list:
	  arg-flag
  | arg-flag-list COMMA arg-flag
  ;

arg-flag:
	  WORD
		  { 
        if (!nate.curMethod().curArg().setArgFlag($WORD))
        {
				  nate.error("Unknown argument type: " + $WORD);
        }
      }
  ;
  
call-return:
  %empty
		  { nate.curMethod().setReturnFlag("none"); }
	| IS type-flags
  ;
  
type-flags:
    type opt-call-return-flags
		  { 
			  nate.curMethod().setType($type);
		  }
  | call-return-flags
  ;

opt-call-return-flags:
    %empty
  | call-return-flags
  ;

call-return-flags:
    OPENPAR 
		call-return-flag-list 
	  CLOSEPAR
  ;

call-return-flag-list:
	  call-return-flag
  | call-return-flag-list COMMA call-return-flag
  ;

call-return-flag:
	  WORD
		  { nate.curMethod().setReturnFlag($WORD); }
  ;

scope-statement:
    SCOPE COL
      { nate.codeStartScope(); }
    BEGIN
      statement-list
    END
      { nate.codeEndScope(); }
  ;

var-statement:
	  var 
		  { lexer.pushState(Lexer::VAR_DECL); }
	  id-list 
		  { lexer.popState(); }
	  is-type var-init-assign
		  { nate.codeDeclareLocalIdentifiers($var, $[id-list], $[is-type], $[var-init-assign]); }
  ;

var:
	  VAR
      { $$ = false; }
  |
    CONST
      { $$ = true; }
  ;

id-list:
	  id
		  { $$.push_back($id); }
  | id-list COMMA id
		  { $$ = $1; $$.push_back($id); }
  ;

id:
	  IDENTIFIER
		  { $$ = ($IDENTIFIER[0] == '$') ? $IDENTIFIER.substr(1) : $IDENTIFIER; }
  ;
  
is-type:
    %empty
		  { $$ = std::make_shared<Type>(""); }
  | IS 
      { lexer.pushState(Lexer::DECL_TYPE); }
    type
	  	{ 
        lexer.popState();
        $$ = $type;
      }
  ;

type:
    WORD type-extra
      { 
        if (!$[type-extra].empty())
        {
          $$ = nate.determineType($WORD);
          $$->setTypenameType(nate.determineType($[type-extra]));
        }
        else
        {
          $$ = nate.determineType($WORD);
        }
      }
  ;

type-extra:
    %empty
  | OF WORD
      { $$ = $WORD; }
  ;

var-init-assign:
	  %empty
		  { $$.clear(); }
  | ASSIGN var-init-list EOS
		  { $$ = $[var-init-list]; }
  ;

var-init-list:
	  var-init
		  { $$.push_back($[var-init]); }
  | var-init-list[list] COMMA var-init
		  { $$ = $list; $$.push_back($[var-init]); }
  ;
  
var-init:
	  expr-at-end-of-statement
  ;

record-statement:
    RECORD WORD[id] COL
      { 
        if (nate.curScope()->getType($id))
        {
				  nate.error("Duplicate type of :" + $id);
        }
        RecordPtr record = std::make_shared<Record>($id);
        nate.curScope()->addRecord(record, $id);
        nate.codeStartRecord(record);
      }
    BEGIN
    record-var-list
    END
      { nate.codeEndRecord(); }
  ;

record-var-list:
    record-var
  | record-var-list record-var
  ;

record-var:
    var
		  { lexer.pushState(Lexer::VAR_DECL); }
	  id-list 
		  { lexer.popState(); }
	  is-type var-init-assign
		  { nate.codeDeclareRecordIdentifiers($var, $[id-list], $[is-type], $[var-init-assign]); }
    opt-eos
  ;

assign-statement:
	  expr-list ASSIGN expr
		  { nate.codeAssign($[expr-list], $expr); }
  ;

expr-list:
	  expr
		  { $$.push_back($expr); }
  | expr-list COMMA expr
		  { $$ = $1; $$.push_back($expr); }
  ;

output-statement:
	  OUTPUT 
		  { 
        nate.codeOutputStart("std::cout");
        lexer.stateExprValue = yy::Lexer::OUTPUT_EXPR;
      }
	  output-list
		  { 
        lexer.stateExprValue = yy::Lexer::EXPR;
        nate.codeOutputEnd(outputEnd);
        outputEnd = true;
      }
  ;

output-list:
	  %empty
  | output-part-list
  ;

output-part-list:
	  output-part
  | output-part output-sep output-part-rest
  ;

output-part-rest:
	  %empty
		  { outputEnd = false; }
  | output-part-list
  ;

output-part:
	  expr
		  { nate.codeOutput($expr); }
  ;

output-sep:
	  COMMA
		  { nate.codeOutput("\" \""); }
	| CONCAT
  ;

input-statement:
	  INPUT 
		  { 
        nate.codeInputStart("std::cin");
        lexer.stateExprValue = yy::Lexer::INPUT_EXPR;
      }
	  input-list
		  { 
        lexer.stateExprValue = yy::Lexer::EXPR;
        nate.codeInputEnd(inputEnd);
        inputEnd = true;
      }
  ;

input-list:
	  %empty
  | input-part-list
  ;

input-part-list:
	  input-part
  | input-part input-sep input-part-rest
  ;

input-part-rest:
	  %empty
		  { inputEnd = false; }
  | input-part-list
  ;

input-part:
	  expr
		  { nate.codeInput($expr); }
  ;

input-sep:
	  COMMA
		  { nate.codeInputSpace(); }
	| CONCAT
		  { nate.codeInputNoSpace(); }
  ;

if-statement:
	  IF expr COL
      { 
        ifExpr.push($expr);
        ifId.push(nate.uniqueName());
      }
    if-rest
      { 
        ifExpr.pop(); 
        ifId.pop(); 
      }
  ;

if-rest:
    if-then
  | if-is
  ;

if-then:
	  BEGIN 
		  { nate.codeIf(ifExpr.top()); }
		  statement-list
		  { nate.codeEndIf(); }
	  END
	  else
  ;

else:
	  %empty
  | ELSE 
	  	{ nate.codeElseIf(); }
		  if-statement
  | ELSE COL 
		  { nate.codeElse(); }
    BEGIN
		statement-list
		  { nate.codeEndIf(); }
	  END
  ;

if-is:
    IS 
	  	{ nate.codeIfIs(ifExpr.top(), ifId.top()); }
    is-rest
    is-else
	  	{ nate.codeEndIfIs(); }
  ;
  
is-rest:
    is-part
    is-block-list
  ;
  
is-block-list:
    is-block
  | is-block-list is-block
  ;

is-block:
    IS is-part
  ;
  
is-part:
    expr COL
	  	{ nate.codeIs($expr, ifExpr.top()); }
    is-part-block
  ;

is-part-block:
    %empty
  | BEGIN 
      { nate.codeBeginIs(); }
    statement-list 
      { nate.codeEndIs(); }
    END
  ;
  
is-else:
    %empty
  | ELSE COL 
	  	{ nate.codeElseIs(); }
    BEGIN 
      { nate.codeBeginIs(); }
    statement-list 
      { nate.codeEndIs(); }
    END
  ;

loop-statement:
	  LOOP 
		  { 
        lexer.pushState(Lexer::LOOP);
        nate.codeInitLoop();
      }
	  for-part
	  opt-while 
    BEGIN
		loop-part-statement-list
		  { 
        nate.codeEndLoop();
        lexer.popState();
      }
    END
  ;

for-part:
	  while-loop-statement
  | for-loop-statement
  | COL
		  { nate.codeStartLoop(); }
  ;

loop-part-statement-list:
	  loop-part-statement
  | loop-part-statement-list loop-part-statement
  ;
  
loop-part-statement:
	  statement
  | while-statement
  ;

while-loop-statement:
	  WHILE expr COL
		  { 
		    nate.codeStartLoop();
			  nate.codeLoopWhile($expr);
		  }
  ;
  
while-statement:
	  WHILE expr COL
		  { nate.codeLoopWhile($expr); }
  ;

opt-while:
	  %empty
  | while-statement
  ;
 
for-loop-statement:
	  FOR VAR 
		  { lexer.pushState(Lexer::VAR_DECL); }
	  id 
		  { 
        forId = $id;
        lexer.popState();
		    lexer.stateExprValue = yy::Lexer::FOR_EXPR;
      }
	  for-part
      { lexer.stateExprValue = yy::Lexer::EXPR; }
	  for-loop-part-end
  ;

for-part:
    for-step
  | for-range
  ;

for-step:
	  is-type ASSIGN 
	  expr[from] for-to expr[to] step 
		  { 
	      if ($[is-type]->is(Type::Abstract))
	      {
		      nate.error("Abstract type: " + $[is-type]->name());
	      }

			  nate.codeStartForStepLoop(forId, $[is-type], $[for-to], $from, $to, $step);
		  }
  ;

for-to:
	  DOWNTO
		  { $$ = true; }
  | TO
		  { $$ = false; }
  ;

step:
	  %empty
		  { $$ = Expr(ExprNode("1", "1", nate.getType("int-32"))); }
  | STEP expr
		  { $$ = $expr; }
  ;

for-loop-part-end:
	  while-statement
  | COL
  ;
  
for-range:
	  IN expr
		  { 
			  nate.codeStartForRangeLoop(forId, $expr);
		  }
  ;

return-statement:
    RETURN expr
      { nate.codeReturn($2); }
  ;
  
expr-statement:
    expr
      { nate.codeExpression($expr); }
  ;

expr:
    expr-part
      { lexer.pushState(lexer.stateExprValue); }
    expr-part-list
    expr-end
      { 
			  lexer.popState(); 
			  $$ = nate.evaluate(Expr($[expr-part], $[expr-part-list]));
        prevWasValue = false;
        lexer.space();
		  }
  ;
  
expr-at-end-of-statement:
    expr-part
      { lexer.pushState(lexer.stateExprValue); }
    expr-part-list
      { 
			  lexer.popState(); 
			  $$ = nate.evaluate(Expr($[expr-part], $[expr-part-list]));
        prevWasValue = false;
        lexer.space();
		  }
  ;
  
expr-end:
    %empty
  | EOS
  ;

expr-part-list:
    %empty
      { $$ = Expr(); }
  | expr-part
  | expr-part-list[list] expr-part
		  { $$ = Expr($[list], $[expr-part]); }
  ;

expr-part:
    expr-word
  | expr-non-word
  ;

expr-non-word:
	  NUMBER
		  { 
        TypePtr type = nate.makeType($NUMBER);
			  $$ = Expr(ExprNode($NUMBER, $NUMBER, type));
			  $$.node().setFlag(ExprNode::Literal, true);
			  $$.node().setFlag(ExprNode::ConstExpr, true);
        lexer.noSpace();
        prevWasValue = true;
		  }
	| FRACTION
		  { 
        TypePtr type = nate.determineType("fraction");
        Fraction temp($FRACTION);
        std::stringstream ss;
        ss << temp.whole() << "," << temp.numerator() << "," << temp.denominator();
			  $$ = Expr(ExprNode($FRACTION, "Fraction(" + ss.str() + ")", type));
			  $$.node().setFlag(ExprNode::Literal, true);
			  $$.node().setFlag(ExprNode::ConstExpr, true);
        lexer.noSpace();
        prevWasValue = true;
		  }
	| string
		  { 
			  $$ = Expr(ExprNode($string, $string, nate.getType("text")));
			  $$.node().setFlag(ExprNode::Literal, true);
			  $$.node().setFlag(ExprNode::ConstExpr, true);
        lexer.noSpace();
        prevWasValue = true;
		  }
  | BOOL
		  { 
			  $$ = Expr(ExprNode($BOOL, $BOOL, nate.getType("boolean")));
			  $$.node().setFlag(ExprNode::Literal, true);
			  $$.node().setFlag(ExprNode::ConstExpr, true);
        lexer.noSpace();
        prevWasValue = true;
		  }
  | id
		  { 
        auto value = nate.alias($id);
        //std::cerr << "Id: " << $id << " " << value << std::endl;
        auto identifier = nate.getOrFakeIdentifier(value);

        if (!lexer.spaceBeen && prevWasValue)
        {
          //std::cerr << "monomial " << value << std::endl;
          $$ = Expr(ExprNode("monomial"));
			    $$.addNode(ExprNode(value, nate.codeId(value), identifier->type()));
        }
        else
        {
			    $$ = Expr(ExprNode(value, nate.codeId(value), identifier->type()));
			    $$.node().setFlag(ExprNode::Output, !identifier->is(Identifier::Const));
          //std::cerr << "spacebeen " << $$ << std::endl;
        }
        prevWasValue = true;
        lexer.noSpace();
        $$.node().setFlag(ExprNode::ConstExpr, identifier->is(Identifier::Const));
		  } 
  | OPENPAR 
      { 
        lexer.space();
        prevWasValue = false;
      }
    expr
    CLOSEPAR
		  { 
        lexer.noSpace();
        prevWasValue = true;
        $$ = nate.evaluate(Expr($expr));

      }
  | IF
		  { 
        $$ = Expr(ExprNode("if"));
        prevWasValue = false;
      }
  | ELSE
		  { 
        $$ = Expr(ExprNode("else"));
        prevWasValue = false;
      }
  ;
  
expr-word:
    WORD
		  { 
        auto value = nate.alias($WORD);

        if (value == "-" && !prevWasValue)
        {
          value = "uminus";
          prevWasValue = false;
          $$ = Expr(value);
        }
        else if (value == "+" && !prevWasValue)
        {
          value = "uplus";
          prevWasValue = false;
          $$ = Expr(value);
        }
        else
        {        
          if (!nate.isLeftMonomial(value) || lexer.spaceBeen || !prevWasValue)
          {
            lexer.space();
            $$ = Expr(value);
          }    
          else
          {
            //std::cerr << "monomial " << value << std::endl;
            $$ = Expr(ExprNode("monomial"));
			      $$.addNode(ExprNode(value));
          }

          prevWasValue = !nate.wantsUnary(value);
          lexer.noSpace();
        }
      }
  ;

string:
	  STRING
  ;

%%

void yy::parser::error(const location& loc, const std::string& msg)
{
  std::cerr << loc << ": " << msg << std::endl;
}