%require "3.2"
%language "c++"
%define api.namespace {yy}
%define api.parser.class {parser}
%define api.value.type variant
%define api.token.constructor
%define parse.error verbose
%defines
%output "parser.cpp"
%locations
%define api.location.file "location.hpp"
%code requires{
  namespace yy {
    class Lexer;  // Generated by reflex with namespace=yy lexer=Lexer lex=yylex
  }
  class NateParser;
  #include "Expr.h"
}
%parse-param { yy::Lexer& lexer } { NateParser& nate }
%code{
  #include "lex.yy.h"  // header file generated with reflex --header-file
  #include "NateParser.h"
  #undef yylex
  #define yylex lexer.lex  // Within bison's parse() we should invoke lexer.yylex(), not the global yylex()

  int stateExprValue = yy::Lexer::EXPR_VALUE;

  void pushState(yy::Lexer& lexer, int aState)
  {
	  lexer.push_state(aState);
	  //std::cerr << "Push " << aState << std::endl;
  }

  void popState(yy::Lexer& lexer)
  {
    //std::cerr << "Pop from " << lexer.top_state();
	  if (!lexer.states_empty())
	  {
		  lexer.pop_state();
	  }

	  if (!lexer.states_empty())
	  {
		  //std::cerr << " to " << lexer.top_state() << std::endl;
	  }
	  else
	  {
		  //std::cerr << std::endl;
	  }
  }
}

%define api.token.prefix {TOK_}
%token <std::string> IDENTIFIER "identifier"
%token <std::string> NUMBER "number"
%token <std::string> STRING "string"
%token <std::string> BOOL "bool"
%token <std::string> WORD "word"
%token EOF 0 "end of file"
%token BEGIN "begin block"
%token END "end block"
%token PROGRAM "program"
%token ERR "error"
%token VAR "var"
%token CODE "code"
%token IF "if"
%token ELSE "else"
%token OUTPUT "output"
%token IS "is"
%token RIGHT "right"
%token LOOP "loop"
%token WHILE "while"
%token FOR "for"
%token DOWNTO "down-to"
%token TO "to"
%token STEP "step"
%token COL ":"
%token ASSIGN ":="
%token EOS "\n"
%token COMMA ","
%token OPENPAR "("
%token CLOSEPAR ")"

%type <std::string>              id;
%type <std::vector<std::string>> id-list;
%type <std::string>              single-id;
%type <std::string>              is-type;
%type <std::string>              type;
%type <std::vector<Expr>>        var-init-assign;
%type <std::vector<Expr>>        var-init-list;
%type <Expr>                     var-init;
%type <bool>                     for-to;
%type <Expr>                     step;
%type <Expr>                     expr;
%type <Expr>					           expr-value-start;
%type <Expr>					           expr-value-next;
%type <Expr>                     expr-value-parts;
%type <Expr>					           expr-value-part;
%type <Expr>					           expr-word-start;
%type <Expr>					           expr-word-next;
%type <Expr>                     expr-word-parts;
%type <Expr>					           expr-word-part;
%type <Expr>					           expr-word;
%type <Expr>					           expr-value;
%type <std::string>              string;

%%

prog-statement-list:
	  prog-statement
  | prog-statement-list prog-statement
  ;

prog-statement:
	  program
  | code
  | BEGIN 
  | END
  | EOS
  ;

program:
	  PROGRAM COL 
		  { nate.codeStartProgram(); }
	  EOS
	  BEGIN 
		  statement-list
	  END
		  { nate.codeEndProgram(); }
  ;

code:
	  CODE 
		  { 
			  nate.addCode();
			  pushState(lexer, Lexer::CODEARG);
		  }
	  code-start
	  code-arg-list IS code-return COL
		  { 
			  popState(lexer);
			  pushState(lexer, Lexer::CODE);
		  }
	  BEGIN
		  code-stat-list
	  END
		  { 
			  popState(lexer); 
			  nate.endCode();
		  }
  ;

code-start:
	  "right" NUMBER 
		  { 
			  nate.curCode().setPriority(atoi($2.c_str())); 
			  nate.curCode().setFlag(Code::RightLeft, true);
		  }
  | NUMBER 
		  { 
			  nate.curCode().setPriority(atoi($1.c_str())); 
		  }
  ;
	
code-return:
	  type
		  { 
			  nate.curCode().setType($1);
		  }
  | code-return-flags 
  ;
  
code-return-flags:
    OPENPAR 
		code-return-flag-list 
	  CLOSEPAR
  ;

code-return-flag-list:
	  code-return-flag
  | code-return-flag-list COMMA code-return-flag
  ;

code-return-flag:
	  WORD
		  { nate.curCode().setReturnFlag($1); }
  ;

code-arg-list:
    code-arg
  | code-arg-list code-arg
  ;

code-arg:
    WORD
		  { nate.curCode().addCodeArgWord($1); }
  | id IS type
		  { 
			  auto id = Identifier($1, Type($3));
			  nate.addIdentifier(id);
		    nate.curCode().addCodeArgId(id);
		  }
  | code-arg-flags
  ;

code-arg-flags:
    id IS OPENPAR 
		{ 
			auto id = Identifier($1, Type(""));
			nate.addIdentifier(id);
		  nate.curCode().addCodeArgId(id);
		}
		code-arg-flag-list 
	  CLOSEPAR
  ;

code-arg-flag-list:
	  code-arg-flag
  | code-arg-flag-list COMMA code-arg-flag
  ;

code-arg-flag:
	  WORD
		  { nate.curCode().curCodeArg().setArgFlag($1); }
  ;

code-stat-list:
    code-stat
  | code-stat-list code-stat
  | BEGIN code-stat-list END
  ;

code-stat:
    WORD
		  { nate.curCode().addCodeStatWord($1); }
  | id
		  { nate.curCode().addCodeStatId($1); }
  ;

statement-list:
    statement
  | statement-list statement
  ;

statement: 
	  var-statement
  | assign-statement
  | output-statement
  | if-statement
  | loop-statement
  | BEGIN statement-list END
  | EOS
  ;

var-statement:
	  var 
		  { pushState(lexer, Lexer::VAR_DECL); }
	  id-list 
		  { popState(lexer); }
	  is-type var-init-assign
		  { nate.codeDeclareLocalIdentifiers($3, $5, $6); }
  ;

var:
	  VAR
  ;

id-list:
	  id
		  { $$.push_back($1); }
  | id-list COMMA id
		  { $$ = $1; $$.push_back($3); }
  ;

id:
	  IDENTIFIER
		  { $$ = ($1[0] == '$') ? $1.substr(1) : $1; }
  ;

single-id:
	  id-list
		  {
			  if ($1.size()>1)
			  {
				  nate.error("Expecting single identifier.");
			  }
			  $$ = $1.front();
		  }
  ;

is-type:
    %empty
		  { $$ = ""; }
  | IS type
	  	{ $$ = $2; }
  ;

type:
    WORD
  ;
  
var-init-assign:
	  %empty
		  { $$.clear(); }
  | ASSIGN var-init-list
		  { $$ = $2; }
  ;

var-init-list:
	  var-init
		  { $$.push_back($1); }
  | var-init-list COMMA var-init
		  { $$ = $1; $$.push_back($3); }
  ;
  
var-init:
	  expr
  ;

assign-statement:
	  id-list ASSIGN expr
		  { nate.codeAssign($1, $3); }
  ;

output-statement:
	  OUTPUT 
		  { nate.codeOutputStart("std::cout"); }
	  output-list 
		  { nate.codeOutputEnd(); }
  ;

output-list:
	  %empty
  | output-part
  | output-list output-sep output-part
  ;

output-part:
	  expr
		  { nate.codeOutput($1); }
  ;

output-sep:
	  COMMA
		  { nate.codeOutput("\" \""); }
  ;

if-statement:
	  IF expr COL
		  { nate.codeIf($2); }
	  EOS BEGIN 
		  statement-list
		  { nate.codeEndIf(); }
	  END
	  else-statement
  ;

else-statement:
	  %empty
  | ELSE 
	  	{ nate.codeElseIf(); }
		  if-statement
  | ELSE COL 
		  { nate.codeElse(); }
    EOS BEGIN
		statement-list
		  { nate.codeEndIf(); }
	  END
  ;

loop-statement:
	  LOOP 
	  for-part
	  EOS opt-while BEGIN
		loop-part-statement-list
		  { nate.codeEndLoop(); }
	  END
  ;

for-part:
	  while-loop-statement
  | for-loop-statement
  | COL
		  { nate.codeStartLoop(); }
  ;

loop-part-statement-list:
	  loop-part-statement
  | loop-part-statement-list loop-part-statement
  ;
  
loop-part-statement:
	  statement
  | while-statement
  ;

while-loop-statement:
	  WHILE expr COL
		  { 
		      nate.codeStartLoop();
			  nate.codeLoopWhile($2);
		  }
  ;
  
while-statement:
	  WHILE expr COL
		  { nate.codeLoopWhile($2); }
  ;

opt-while:
	  %empty
  | while-statement EOS
  ;

for-loop-statement:
	  FOR var 
		  { pushState(lexer, Lexer::VAR_DECL); }
	  single-id 
		  { popState(lexer); }
	  is-type ASSIGN 
		  { stateExprValue = yy::Lexer::FOR_EXPR_VALUE; }
	  expr[from] for-to expr[to] step 
		  { 
			  stateExprValue = yy::Lexer::EXPR_VALUE;
			  nate.codeStartForLoop($[single-id], $[is-type], $[for-to], $from, $to, $step);
		  }
	  for-loop-part-end
  ;
  
for-to:
	  DOWNTO
		  { $$ = true; }
  | TO
		  { $$ = false; }
  ;

step:
	  %empty
		  { $$ = Expr(ExprNode("1", "1", Type("int-32"))); }
  | STEP expr
		  { $$ = $expr; }
  ;

for-loop-part-end:
	  while-statement
  | COL
  ;

expr:
	  expr-value-start
	  expr-value-parts
	  expr-end
		  { 
			  popState(lexer); 
			  $$ = nate.evaluate(Expr($[expr-value-start], $[expr-value-parts]));
		  }
 |	expr-word-start
	  expr-word-parts
	  expr-end
		  { 
			  popState(lexer); 
			  $$ = nate.evaluate(Expr($1, $2));
		  }
  ;

expr-end:
	  %empty
  | EOS
  ;

expr-value-parts:
	  %empty
		  { $$ = Expr(); }
  | expr-value-next expr-word-parts
		  { $$ = Expr($1, $2); }
  ;
  
expr-value-start:
	  expr-value
		  { $$ = $1; pushState(lexer, stateExprValue); }
  ;
  
expr-value-next:
	  expr-word-part
		  { $$ = Expr($1.node().text() == "+" ? "plus" : ($1.node().text() == "-" ? "minus" : $1.node().text())); }
  ;

expr-value-part:
	  expr-value
		  { $$ = $1; popState(lexer); pushState(lexer, stateExprValue); }
  ;

expr-value:
	  NUMBER
		  { 
			  $$ = Expr(ExprNode($1, $1, Type::makeType($1)));
			  $$.node().setFlag(ExprNode::Literal, true);
		  }
  | string
		  { 
			  $$ = Expr(ExprNode($1, $1, Type::makeType($1)));
			  $$.node().setFlag(ExprNode::Literal, true);
		  }
  | BOOL
		  { 
			  $$ = Expr(ExprNode($1, $1, Type::makeType($1)));
			  $$.node().setFlag(ExprNode::Literal, true);
		  }
  | id
		  { 
			  $$ = Expr(ExprNode($1, nate.codeId($1), nate.getOrFakeIdentifier($1).type()));
			  $$.node().setFlag(ExprNode::Output, true);
		  } 
  | OPENPAR expr CLOSEPAR
		  { $$ = nate.evaluate(Expr($2)); }
  ;

expr-word-parts:
	  %empty
		  { $$ = Expr(); }
  | expr-word-next expr-word-parts
	  	{ $$ = Expr($1, $2); }
  | expr-value-part expr-value-parts
	  	{ $$ = Expr($1, $2); }
  ;
    
expr-word-start:
	  expr-word
		  { $$ = $1; pushState(lexer, Lexer::EXPR_WORD); }
  ;
  
expr-word-next:
	  expr-word-part
  ;

expr-word-part:
	  expr-word
		  { $$ = $1; popState(lexer); pushState(lexer, Lexer::EXPR_WORD); }
  | IF
		  { $$ = Expr(ExprNode("if")); popState(lexer); pushState(lexer, Lexer::EXPR_WORD); }
  | ELSE
		  { $$ = Expr(ExprNode("else")); popState(lexer); pushState(lexer, Lexer::EXPR_WORD); }
  ;

expr-word:
    WORD
		  { $$ = Expr($1); }
  ;

string:
	  STRING
  ;

%%

void yy::parser::error(const location& loc, const std::string& msg)
{
  std::cerr << loc << ": " << msg << std::endl;
}