%require "3.2"
%language "c++"
%define api.namespace {yy}
%define api.parser.class {parser}
%define api.value.type variant
%define api.token.constructor
%define parse.error verbose
%defines
%output "parser.cpp"
%locations
%define api.location.file "location.hpp"
%code requires{
  #pragma warning(disable:4065)
  namespace yy {
    class Lexer;  // Generated by reflex with namespace=yy lexer=Lexer lex=yylex
  }
  class NateParser;
  #include "Expr.h"
  #include "Type.h"
  #include "core/Rational.h"
}
%parse-param { yy::Lexer& lexer } { NateParser& nate }
%code{
  #include "lex.yy.h"  // header file generated with reflex --header-file
  #include "NateParser.h"
  #undef yylex
  #define yylex lexer.lex  // Within bison's parse() we should invoke lexer.yylex(), not the global yylex()
  
  void copyParsedCodes(NateParser& aNate)
  {
    for (auto code : aNate.data.curParsedCodes)
    {
      if (aNate.curCode() != code)
      {
        code->copyFrom(*aNate.curCode());
      }
    }

    aNate.data.curParsedCodes.clear();
  }
}

%define api.token.prefix {TOK_}
%token <std::string> IDENTIFIER "identifier"
%token <std::string> NUMBER "number"
%token <std::string> RATIONAL "rational"
%token <std::string> STRING "string"
%token <std::string> BOOL "bool"
%token <std::string> WORD "word"
%token EOF 0 "end of file"
%token BEGIN "begin block"
%token END "end block"
%token ALIAS "alias"
%token IMPORT "import"
%token PROGRAM "program"
%token SCOPE "scope"
%token VAR "var"
%token PROP "property"
%token GET "get"
%token SET "set"
%token CONST "const"
%token DECLARE "declare"
%token IMPLEMENT "implement"
%token ROLE "role"
%token OBJECT "object"
%token CODE "code"
%token MATH "math"
%token DEFINE "define"
%token IF "if"
%token ELSE "else"
%token OUTPUT "output"
%token ERROR "error"
%token INPUT "input"
%token WRITE "write"
%token READ "read"
%token IS "is"
%token AS "as"
%token OF "of"
%token IN "in"
%token LOOP "loop"
%token WHILE "while"
%token FOR "for"
%token DOWNTO "down-to"
%token TO "to"
%token FROM "from"
%token STEP "step"
%token RETURN "return"
%token RECORD "record"
%token DATA "data"
%token COL ":"
%token ASSIGN ":="
%token EOS "\n"
%token COMMA ","
%token CONCAT "&"
%token OPENPAR "("
%token CLOSEPAR ")"
%token ARGSTART "${"
%token ARGEND "}"
%token BADTOKEN

%type <std::string>              id;
%type <std::string>              arg-id;
%type <std::vector<std::string>> id-list;
%type <TypePtr>                  optional-is-type;
%type <std::vector<std::string>> opt-flag-list;
%type <std::vector<std::string>> flag-list;
%type <std::string>              flag;
%type <TypePtr>                  is-type;
%type <TypePtr>                  type;
%type <std::string>              type-extra;
%type <bool>                     var;
%type <std::vector<Expr>>        var-init-assign;
%type <std::vector<Expr>>        var-init-list;
%type <std::vector<Expr>>        expr-list;
%type <Expr>                     var-init;
%type <bool>                     for-to;
%type <Expr>                     step;
%type <Expr>                     expr;
%type <Expr>                     definitely-expr;
%type <Expr>                     inline-expr;
%type <Expr>                     expr-at-end-of-statement;
%type <Expr>                     expr-part;
%type <Expr>                     expr-part-list;
%type <Expr>					           expr-non-word;
%type <Expr>					           expr-word;
%type <std::string>              string;
%type <Expr>                     write-sink;
%type <Expr>                     read-source;
%type <bool>                     output-list;
%type <bool>                     output-part-list;
%type <bool>                     output-part-rest;
%type <bool>                     input-list;
%type <bool>                     input-part-list;
%type <bool>                     input-part-rest;

%%

prog-statement-list:
	  prog-statement
  | prog-statement-list prog-statement
  ;

prog-statement:
	  import-statement
  | alias-statement
  | program-statement
  | code-statement
  | define-statement
  | record-statement
  | var-statement
  | data-statement
  | role-statement
  | declare-object-statement
  | implement-object-statement
  | EOS
  ;
  
opt-eos:
    %empty
  | EOS opt-eos
  ;

alias-statement:
    ALIAS STRING[STR1] STRING[STR2]
      { nate.addAlias(unquote($STR1), unquote($STR2)); }
  ;

import-statement:
    IMPORT WORD
      { nate.import($WORD); }
  ;

col:
    COL opt-eos
  ;

begin:
    EOS begin
  | BEGIN
  ;
  
end:
    END
  ;

program-statement:
	  PROGRAM col 
		  { nate.startProgram(@PROGRAM); }
	  begin 
		  statement-list
	  end
      { nate.endProgram(@end); }
  ;
  
statement-list:
    statement
  | statement-list statement
  ;

statement: 
	  var-statement
  | scope-statement
  | assign-statement
  | output-statement
  | error-statement
  | input-statement
  | data-statement
  | write-statement
  | read-statement
  | if-statement
  | loop-statement
  | return-statement
  | record-statement
  | expr-statement
  | math-statement
  | EOS
  ;
  
role-statement:
	  ROLE 
		  { 
        nate.data.inObject = true;
        lexer.pushState(Lexer::VAR_DECL);
      }
	  id 
		  { 
        auto object = std::make_shared<Object>($id, nate.getType("object"));
        object->setCodeType(toCodeName($id));
        object->setFlag(Type::Abstract, true);
        object->setFlag(Type::Unknown, false);
        object->setIsRole(true);
        nate.addObject(object);
      }
    opt-as-roles
      {
        lexer.popState();
        nate.checkObject(nate.curObject());
        nate.codeStartDeclObject(@id);
		  }
    col
	  begin
		  declare-object-content-statement-list
	  end
		  { 
        nate.endDeclObject();
		  }
  ;

declare-object-statement:
	  DECLARE OBJECT 
		  { 
        nate.data.inObject = true;
        lexer.pushState(Lexer::VAR_DECL);
      }
	  id 
		  { 
        auto object = std::make_shared<Object>($id, nate.getType("object"));
        object->setCodeType(toCodeName($id));
        object->setFlag(Type::Abstract, false);
        object->setFlag(Type::Unknown, false);
        nate.addObject(object);
      }
    base-classes
      {
        lexer.popState();
        nate.checkObject(nate.curObject());
        nate.codeStartDeclObject(@id);
		  }
    col
	  begin
		  declare-object-content-statement-list
	  end
		  { 
        nate.endDeclObject();
		  }
  ;
  
base-classes:
    %empty
  | IS base-class opt-as-roles
  | as-roles
  ;

opt-as-roles:
    %empty
  | as-roles
  ;

as-roles:
    AS role-list
  ;

role-list:
    role
  | role-list COMMA role
  ;

base-class:
    id
      {
        nate.importBaseObject($id);
        nate.addObjectBase(nate.getObject($id));
      }
  ;
  
role:
    id
      {
        nate.importBaseObject($id);
        nate.addObjectRole(nate.getObject($id));
      }
  ;

declare-object-content-statement-list:
    declare-object-content-statement
  | declare-object-content-statement-list declare-object-content-statement
  ;

declare-object-content-statement:
	  record-statement
	| property-declare-statement
  | define-decl
			{ 
			  lexer.popState();
			  nate.declareDefine(true);
        nate.endDefine();
      }
  | EOS
  ;
  
implement-object-statement:
	  IMPLEMENT OBJECT 
		  { 
        nate.data.inObject = true;
        lexer.pushState(Lexer::VAR_DECL);
      }
	  id 
		  { 
        lexer.popState();
        auto objectDecl = nate.getObject($id);
        bool existingObjectDecl = objectDecl && !objectDecl->is(Type::ObjectImpl);
        if (!existingObjectDecl)
        {
          auto object = std::make_shared<Object>($id, nate.getType("object"));
          object->setCodeType(toCodeName($id));
          object->setFlag(Type::Abstract, false);
          object->setFlag(Type::Unknown, false);
          object->setFlag(Type::ObjectImpl);
          
          nate.addObject(object);
          nate.checkObject(object);
          nate.codeStartImplObject(@id);
        }
        else
        {
          nate.startObject(objectDecl);
          nate.codeStartImplObject(@id);
        }
		  }
    col
	  begin
		  implement-object-content-statement-list
	  end
		  { 
        nate.data.inObject = false;
        nate.codeEndImplObject();
			  nate.endImplementObject();
		  }
  ;
  
implement-object-content-statement-list:
    implement-object-content-statement
  | implement-object-content-statement-list implement-object-content-statement
  ;

implement-object-content-statement:
	  record-statement
	| property-define-statement
  | define-statement
  | impl-var-statement
  | EOS
  ;

define-decl:
	  DEFINE 
		  { 
			  nate.addDefine(nate.data.inObject);
			  lexer.pushState(Lexer::ARGS);
        nate.data.objectMe = false;
		  }
	  arg-list 
      { nate.data.flagsHolder = nate.curMethod().get(); }
    call-return
  ;
  
arg-list:
    arg
  | arg-list arg
  ;
  
arg:
    WORD
		  { nate.addArgWord($WORD); }
  | ARGSTART arg-id[id] optional-is-type 
		  { 
        nate.addArgId($id, $[optional-is-type], "");
        nate.data.flagsHolder = &nate.curMethod()->curArg();
      }
    opt-holder-flag-list
    ARGEND
  ;
    
define-statement:
	  define-decl COL
		  { 
			  lexer.popState();
			  lexer.pushState(Lexer::DEFINE);
			  nate.declareDefine(false/*aIsDecl*/);
		  }
	  begin
		  statement-list
	  end
		  { 
			  lexer.popState(); 
			  nate.endDefine();
		  }
  ;
  
code-statement:
    code-define
  | code-include
  ;

code-include:
    CODE COL
		  { 
			  nate.addCode();
			  lexer.pushState(Lexer::CODE);
		  }
	  begin
		  code-stat-list
	  end
		  { 
			  lexer.popState();
			  nate.endCode();
        nate.codeCodeInclude();
		  }
  ;

code-define:
	  CODE DEFINE
		  { 
			  nate.addCode();
        nate.data.curParsedCodes.push_back(nate.curCode());
			  lexer.pushState(Lexer::ARGS);
		  }
	  code-start
	  code-list 
      { nate.data.flagsHolder = nate.curMethod().get(); }
    call-return COL
		  { 
			  lexer.popState();
			  lexer.pushState(Lexer::CODE);
		  }
	  begin
		  code-stat-list
	  end
		  { 
			  lexer.popState();
			  nate.endCode();
        copyParsedCodes(nate);
		  }
  ;

code-list:
    code-arg-list
  | code-list COMMA opt-eos
      {
			  nate.endCode();
			  nate.addCode();
        nate.data.curParsedCodes.push_back(nate.curCode());
      }
    code-arg-list
  ;
  
code-start:
    NUMBER 
		  { 
			  nate.curCode()->setPriority(atoi($NUMBER.c_str())); 
		  }
  ;

code-stat-list:
    code-stat
  | code-stat-list code-stat
  | begin code-stat-list end
  ;

code-stat:
    WORD
		  { nate.curCode()->addCodeStatWord($WORD); }
  | id
		  { nate.curCode()->addCodeStatId($id); }
  ;
  
code-arg-list:
    code-arg
  | code-arg-list code-arg
  ;

code-arg:
    arg
  | code-id-with-arg-flags
  ;
  
code-id-with-arg-flags:
    ARGSTART arg-id[id] AS
		  { 
			  auto id = std::make_shared<Identifier>(nate.curIdentifiersHolder(), $id, std::make_shared<Type>(""));
			  nate.addIdentifier(id);
		    nate.curMethod()->addArgId(id);
        nate.data.flagsHolder = &nate.curMethod()->curArg();
		  }
		holder-flag-list 
    ARGEND
  ;
 
arg-id:
    id
  | WORD
  ;
             
call-return:
  %empty
		  { nate.curMethod()->setFlagString("none"); }
	| type-flags
  ;
  
type-flags:
    IS type 
		  { 
			  nate.curMethod()->setType($type);
		  }
    opt-holder-flag-list
  | AS holder-flag-list
  ;
  
math-statement:
    MATH COL
		  { 
			  nate.startMath(@MATH);
			  lexer.pushState(Lexer::MATH);
		  }
	  begin
		  math-stat-list
	  end
		  { 
			  lexer.popState();
			  nate.endMath();
		  }
  ;
  
math-stat-list:
    math-stat
  | math-stat-list math-stat
  ;

math-stat:
    %empty
  | begin math-stat-list end
  | WORD
		  { nate.addMathStatWord($WORD, @WORD); }
  ;

property-declare-statement:
	  PROP 
		  { lexer.pushState(Lexer::VAR_DECL); }
	  id-list 
      { lexer.popState(); }
	  is-type opt-flag-list
		  { nate.declareProperties($[id-list], $[is-type], $[opt-flag-list], @PROP); }
  ;
  
property-define-statement:
	  PROP 
		  { lexer.pushState(Lexer::VAR_DECL); }
    id COL
      { 
		    lexer.popState(); 
        nate.data.propId = nate.getOrFakeIdentifier($id, nate.curIdentifiersHolder().get());

      }
	  begin
      property-get-set-list
    end
      { nate.data.propId = IdentifierPtr(); }
  ;

property-get-set-list:
    property-get-set-code
  | property-get-set-list property-get-set-code
  ;
  
property-get-set-code:
    property-get-code
  | property-set-code
  ;

property-get-code:
    GET COL
		  { 
			  lexer.pushState(Lexer::DEFINE);
			  nate.defineProp(nate.data.propId, Object::PropType::Get);
		  }
	  begin
		  statement-list
	  end
		  { 
			  lexer.popState(); 
			  nate.endDefineProp(nate.data.propId, Object::PropType::Get);
		  }
  ;
  
property-set-code:
    SET COL
		  { 
			  lexer.pushState(Lexer::DEFINE);
			  nate.defineProp(nate.data.propId, Object::PropType::Set);
		  }
	  begin
		  statement-list
	  end
		  { 
			  lexer.popState(); 
			  nate.endDefineProp(nate.data.propId, Object::PropType::Set);
		  }
  ;
  
opt-holder-flag-list:
    opt-flag-list
      { nate.data.flagsHolder->setFlagStrings($[opt-flag-list]); }
  ;
  
holder-flag-list:
    flag-list
      { nate.data.flagsHolder->setFlagStrings($[flag-list]); }
  ;

opt-flag-list:
    %empty
      { $$ = {}; }
  | AS flag-list
      { $$ = $[flag-list]; }
  ;

flag-list:
	  flag
		  { $$.push_back($flag); }
  | flag-list[list] COMMA flag
		  { $$ = $list; $$.push_back($flag); }
  ;

flag:
	  WORD
  ;  

scope-statement:
    SCOPE col
      { nate.codeStartScope(); }
    begin
      statement-list
    end
      { nate.codeEndScope(); }
  ;

impl-var-statement:
      { nate.data.inObjectImpl = true; }
    var-statement
      { nate.data.inObjectImpl = false; }
  ;

var-statement:
	  var 
		  { lexer.pushState(Lexer::VAR_DECL); }
	  id-list 
		  { lexer.popState(); }
	  optional-is-type var-init-assign
		  { 
        nate.declareLocalIdentifiers($var, $[id-list], $[optional-is-type], $[var-init-assign],
                                     NateParser::InitializeVariables, @var);
      }
  ;

var:
	  VAR
      { $$ = false; }
  |
    CONST
      { $$ = true; }
  ;

id-list:
	  id
		  { $$.push_back($id); }
  | id-list[list] COMMA id
		  { $$ = $list; $$.push_back($id); }
  ;

id:
	  IDENTIFIER
		  { $$ = ($IDENTIFIER[0] == '$') ? $IDENTIFIER.substr(1) : $IDENTIFIER; }
  ;
  
optional-is-type:
    %empty
		  { $$ = std::make_shared<Type>(""); }
  | is-type 
  ;

is-type:
    IS 
      { lexer.pushState(Lexer::DECL_TYPE); }
    type
	  	{ 
        lexer.popState();
        $$ = $type;
      }
  ;

type:
    WORD type-extra
      { 
        if (!$[type-extra].empty())
        {
          $$ = nate.determineType($WORD);
          if ($$->is(Type::Template))
          {
            $$ = std::make_shared<Type>(*$$); // clone
            $$->setTypenameType(nate.determineType($[type-extra]));
          }
          else
          {
            nate.error("Not a template: " + $WORD);
          }
        }
        else
        {
          $$ = nate.determineType($WORD);
        }
      }
  ;

type-extra:
    %empty
      { $$ = ""; }
  | OF WORD
      { $$ = $WORD; }
  ;

var-init-assign:
	  %empty
		  { $$.clear(); }
  | ASSIGN var-init-list EOS
		  { $$ = $[var-init-list]; }
  ;

var-init-list:
	  var-init
		  { $$.push_back($[var-init]); }
  | var-init-list[list] COMMA var-init
		  { $$ = $list; $$.push_back($[var-init]); }
  ;
  
var-init:
	  expr-at-end-of-statement
  ;

record-statement:
    RECORD WORD[id] col
      { 
        if (nate.curTypesHolder()->types().get($id))
        {
				  nate.error("Duplicate type of :" + $id);
        }
        RecordPtr record = std::make_shared<Record>($id);
        nate.curRecordsHolder()->records().add(record, $id);
        nate.codeStartRecord(record, @col);
      }
    begin
      record-var-list
    end
      { nate.codeEndRecord(@end); }
  ;

record-var-list:
    record-var
  | record-var-list record-var
  ;

record-var:
    var
		  { lexer.pushState(Lexer::VAR_DECL); }
	  id-list 
		  { lexer.popState(); }
	  optional-is-type var-init-assign
		  { nate.declareRecordIdentifiers($var, $[id-list], $[optional-is-type], $[var-init-assign], @var); }
    opt-eos
  ;

assign-statement:
	  expr-list ASSIGN expr
		  { 
        nate.doAssign($[expr-list], $expr, @ASSIGN);
      }
  ;

expr-list:
    expr
		  { $$.push_back($expr); }
  | expr-list[list] COMMA expr
		  { $$ = $list; $$.push_back($expr); }
  ;
  
data-statement:
	  DATA 
		  { lexer.pushState(Lexer::VAR_DECL); }
    id 
		  { lexer.popState(); }
    col
		  { 
        nate.codeDataStart($id, @DATA);
      }
    begin
      data-list
    end
      { nate.codeDataEnd($id, @begin); }
  ;
  
data-list:
    output-list 
		  { 
        nate.codeOutputEnd($[output-list]);
      }
  | data-list opt-eos output-list 
		  { 
        nate.codeOutputEnd($[output-list]);
      }
  ;

output-statement:
	  OUTPUT 
		  { 
        nate.addStat(ByteCode::StdOutput, @OUTPUT);
      }
	  output-list
		  { 
        nate.up();
      }
  ;
  
error-statement:
	  ERROR 
		  { 
        nate.codeOutputStart("std::cerr", @ERROR);
      }
	  output-list
		  { 
        nate.codeOutputEnd($[output-list]);
      }
  ;
  
write-statement:
	  WRITE write-sink COL
      {
        nate.codeWriteStart($[write-sink], @WRITE);
        if (!$[write-sink].isEmpty())
        {
          nate.data.prevWriteSink = $[write-sink].code();
        }
      }
	  output-list
		  { 
        nate.codeOutputEnd($[output-list]);
      }
  ;
  
write-sink:
    %empty
		  { 
        $$ = Expr();
      }
  | TO definitely-expr[expr]
		  { 
        $$ = $expr;
      }
  ;
    
read-statement:
	  READ read-source COL
      {
        nate.codeReadStart($[read-source], @READ);
        if (!$[read-source].isEmpty())
        {
          nate.data.prevReadSource = $[read-source].code();
        }
      }
	  input-list
		  { 
        nate.codeInputEnd($[input-list]);
      }
  ;
  
read-source:
    %empty
		  { 
        $$ = Expr();
      }
  | FROM definitely-expr[expr]
		  { 
        $$ = $expr;
      }
  ;

output-list:
	  %empty
		  { $$ = true; }
  | output-part-list
		  { $$ = $[output-part-list]; }
  ;

output-part-list:
	  output-part
		  { $$ = true; }
  | output-part output-sep output-part-rest
		  { $$ = $[output-part-rest]; }
  ;

output-part-rest:
	  %empty
		  { $$ = false; }
  | output-part-list
		  { $$ = $[output-part-list]; }
  ;

output-part:
	  expr
		  { 
        if ($expr.type() && !$expr.type()->empty())
        {
          nate.add(ByteCode::Expr, $expr, @expr);
        }
        else
        {
          nate.error("Cannot have typeless expression");
        }
      }
  ;

output-sep:
	  COMMA
		  { nate.add(ByteCode::OutputSepComma, @COMMA); }
	| CONCAT
		  { nate.add(ByteCode::OutputSepConcat, @CONCAT); }
  ;

input-statement:
	  INPUT 
		  { 
        nate.codeInputStart("std::cin", @INPUT);
      }
	  input-list
		  { 
        nate.codeInputEnd($[input-list]);
      }
  ;

input-list:
	  %empty
      { $$ = true; }
  | input-part-list
      { $$ = $[input-part-list]; }
  ;

input-part-list:
	  input-part
      { $$ = true; }
  | input-part input-sep input-part-rest
      { $$ = $[input-part-rest]; }
  ;

input-part-rest:
	  %empty
		  { $$ = false; }
  | input-part-list
		  { $$ = $[input-part-list]; }
  ;

input-part:
	  expr
		  { nate.codeInput($expr); }
  ;

input-sep:
	  COMMA
		  { nate.codeInputSpace(); }
	| CONCAT
		  { nate.codeInputNoSpace(); }
  ;

if-statement:
	  IF expr col
      { 
        nate.data.ifExpr.push($expr);
        nate.data.ifId.push(nate.uniqueName());
        nate.data.ifLocation.push(@expr);
      }
    if-rest
      { 
        nate.data.ifExpr.pop(); 
        nate.data.ifId.pop(); 
        nate.data.ifLocation.pop(); 
      }
  ;

if-rest:
    if-then
  | if-is
  ;

if-then:
	  begin 
		  { nate.doIf(nate.data.ifExpr.top(), nate.data.ifLocation.top()); }
		  statement-list
	  end
	  else
  ;

else:
	  %empty
		  { nate.doEndIf(@else); }
  | ELSE 
	  	{ nate.doElseIf(@ELSE); }
		  if-statement
  | ELSE col 
		  { nate.doElse(@ELSE); }
    begin
		  statement-list
	  end
		  { nate.doEndIf(@end); }
  ;

if-is:
    IS 
	  	{ 
        nate.doIfIs(nate.data.ifExpr.top(), nate.data.ifId.top(), @IS);
        nate.doCaseIsList(@IS);
      }
    is-rest
    is-else
		  { nate.doEndIs(@[is-else]); }
  ;
  
is-rest:
    is-part
    is-block-list
  ;
  
is-block-list:
    is-block
  | is-block-list is-block
  ;

is-block:
    IS is-part
  ;
  
is-part:
    expr col
	  	{ 
        nate.doCaseIs($expr, nate.data.ifExpr.top(), @expr);
      }
    is-part-block
  ;

is-part-block:
    %empty
  | begin 
      statement-list 
    end
      { 
        nate.up();
        nate.doCaseIsList(@end);
      }
  ;
  
is-else:
    %empty
  | ELSE col 
	  	{ 
        nate.up();
        nate.doElseIs(@ELSE);
      }
    begin 
      statement-list 
    end
  ;

loop-statement:
	  LOOP 
		  { 
        lexer.pushState(Lexer::LOOP);
        nate.doInitLoop(@LOOP);
      }
	  for-part
	  opt-while 
    begin
		loop-part-statement-list
    end
		  { 
        nate.doEndLoop(@end);
        lexer.popState();
      }
  ;

for-part:
	  while-loop-statement
  | for-loop-statement
  | col
		  { nate.doStartLoop(@col); }
  ;

loop-part-statement-list:
	  loop-part-statement
  | loop-part-statement-list loop-part-statement
  ;
  
loop-part-statement:
	  statement
  | while-statement
  ;

while-loop-statement:
	  WHILE expr col
		  { 
		    nate.doStartLoop(@col);
			  nate.doWhile($expr, @WHILE);
		  }
  ;
  
while-statement:
	  WHILE expr col
		  { nate.doWhile($expr, @WHILE); }
  ;

opt-while:
	  %empty
  | while-statement
  ;
 
for-loop-statement:
	  FOR VAR 
		  { lexer.pushState(Lexer::FOR_VAR_DECL); }
	  id 
		  { 
        nate.data.forId = $id;
        lexer.popState();
		    lexer.stateExprValue = yy::Lexer::FOR_EXPR;
      }
	  for-part
      { lexer.stateExprValue = yy::Lexer::EXPR; }
	  for-loop-part-end
  ;

for-part:
    for-step
  | for-range
  ;

for-step:
	  optional-is-type ASSIGN 
	  expr[from] for-to expr[to] step 
		  { 
	      if ($[optional-is-type]->is(Type::Abstract))
	      {
		      nate.error("Abstract type: " + $[optional-is-type]->name());
	      }

			  nate.doStartLoopForStep(nate.data.forId, $[optional-is-type], $[for-to], $from, $to, $step, @ASSIGN);
		  }
  ;

for-to:
	  DOWNTO
		  { $$ = true; }
  | TO
		  { $$ = false; }
  ;

step:
	  %empty
		  { $$ = Expr(ExprNode("1", "1", nate.getType("int-32"))); }
  | STEP expr
		  { $$ = $expr; }
  ;

for-loop-part-end:
	  while-statement
  | col
  ;
  
for-range:
	  IN expr
		  { 
			  nate.doStartLoopForRange(nate.data.forId, $expr, @IN);
		  }
  ;

return-statement:
    RETURN expr
      { nate.codeReturn($2, @RETURN); }
  ;
  
expr-statement:
    expr
      { 
        nate.codeExpressionStatement($expr, @expr);
        if ($expr.type() && !$expr.type()->empty())
        {
          nate.warning("Ignoring result of expression");
        }
      }
  ;
  
definitely-expr:
      { lexer.pushState(lexer.stateExprValue); }
    expr
      { 
        lexer.popState();
        $$ = $expr;
      }
  ;

expr:
    inline-expr
    expr-end
      { $$ = $[inline-expr]; }
  ;

inline-expr:
    expr-part
      { lexer.pushState(lexer.stateExprValue); }
    expr-part-list
      { 
			  lexer.popState(); 
			  $$ = nate.evaluate(Expr($[expr-part], $[expr-part-list]));
        nate.data.prevWasValue = false;
        lexer.space();
		  }
  ;
  
expr-at-end-of-statement:
    inline-expr
  ;
  
expr-end:
    %empty
  | EOS
  ;

expr-part-list:
    %empty
      { $$ = Expr(); }
  | expr-part
  | expr-part-list[list] expr-part
		  { $$ = Expr($[list], $[expr-part]); }
  ;

expr-part:
    expr-word
  | expr-non-word
  ;

expr-non-word:
	  NUMBER
		  { 
        auto number = $NUMBER;
        TypePtr type = nate.getNumberType(number);
			  $$ = Expr(ExprNode($NUMBER, number, type));
			  $$.node().setFlag(ExprNode::Literal, true);
			  $$.node().setFlag(ExprNode::ConstExpr, true);
        lexer.noSpace();
        nate.data.prevWasValue = true;
		  }
	| RATIONAL
		  { 
        TypePtr type = nate.determineType("rational");
        Rational temp($RATIONAL);
        std::stringstream ss;
        ss << temp.whole() << "," << temp.numerator() << "," << temp.denominator();
			  $$ = Expr(ExprNode($RATIONAL, "Rational(" + ss.str() + ")", type));
			  $$.node().setFlag(ExprNode::Literal, true);
			  $$.node().setFlag(ExprNode::ConstExpr, true);
        lexer.noSpace();
        nate.data.prevWasValue = true;
		  }
	| string
		  { 
			  $$ = Expr(ExprNode($string, $string, nate.getType("text")));
			  $$.node().setFlag(ExprNode::Literal, true);
			  $$.node().setFlag(ExprNode::ConstExpr, true);
        lexer.noSpace();
        nate.data.prevWasValue = true;
		  }
  | BOOL
		  { 
			  $$ = Expr(ExprNode($BOOL, $BOOL, nate.getType("boolean")));
			  $$.node().setFlag(ExprNode::Literal, true);
			  $$.node().setFlag(ExprNode::ConstExpr, true);
        lexer.noSpace();
        nate.data.prevWasValue = true;
		  }
  | id
		  { 
        auto value = nate.alias($id);
        //std::cerr << "Id: " << $id << " " << value << std::endl;
        auto identifier = nate.getOrFakeIdentifier(value);

        if (!lexer.spaceBeen && nate.data.prevWasValue)
        {
          //std::cerr << "monomial " << value << std::endl;
          $$ = Expr(ExprNode("monomial"));
			    $$.addNode(ExprNode(identifier));
        }
        else
        {
			    $$ = Expr(ExprNode(identifier));
			    $$.node().setFlag(ExprNode::Output, !identifier->is(Identifier::Const));
          //std::cerr << "spacebeen " << $$ << std::endl;
        }

        nate.data.prevWasValue = true;
        lexer.noSpace();
		  } 
  | OPENPAR 
      { 
        lexer.space();
        nate.data.prevWasValue = false;
      }
    expr
    CLOSEPAR
		  { 
        lexer.noSpace();
        nate.data.prevWasValue = true;
        $$ = Expr::parenthesized($expr);

      }
  | IF
		  { 
        $$ = Expr(ExprNode("if"));
        nate.data.prevWasValue = false;
      }
  | ELSE
		  { 
        $$ = Expr(ExprNode("else"));
        nate.data.prevWasValue = false;
      }
  ;
  
expr-word:
    WORD
		  { 
        auto value = nate.alias($WORD);

        if (value == "-" && !nate.data.prevWasValue)
        {
          value = "uminus";
          nate.data.prevWasValue = false;
          $$ = Expr(value);
        }
        else if (value == "+" && !nate.data.prevWasValue)
        {
          value = "uplus";
          nate.data.prevWasValue = false;
          $$ = Expr(value);
        }
        else
        {        
          if (!nate.isLeftMonomial(value) || lexer.spaceBeen || !nate.data.prevWasValue)
          {
            lexer.space();
            $$ = Expr(value);
          }    
          else
          {
            //std::cerr << "monomial " << value << std::endl;
            $$ = Expr(ExprNode("monomial"));
			      $$.addNode(ExprNode(value));
          }

          nate.data.prevWasValue = !nate.wantsUnary(value);
          lexer.noSpace();
        }
      }
  ;

string:
	  STRING
  ;

%%

void yy::parser::error(const location& loc, const std::string& msg)
{
  std::cerr << nate.getLexer()->currentFile() << " " << loc << ": " << msg;
  if (nate.getLexer()->has_matcher())
  {
    std::cerr << " (" << nate.getLexer()->text() << ")";
  }
  
  std::cerr << std::endl;
}