PROJECT_NAME := MathParser
TARGET_KIND := lib
TARGET_PATH := $(MATHPARSER_LIB)

INCLUDE_DIRS := ../NateLib/utf8
SOURCES := CppMathParser.cpp MathParser.cpp MathTypes.cpp

include ../build/common.mk
